### ISSUE TITLE
Decent Scale will only report values if you send some command

### ISSUE THREAD

**Issue by reox** [lucapinello/pydecentscale#1]
Hi!
thanks for your library, I wanted to do the same but you now have a head start ;)

I found out that the decent scale (at least my one) will only send weight data if you previously send some command. (does your does the same?)
This is also implicitly written in the documentation (Quick Guide, Step 3)
I first thought my scale is broken, because it did not send any weight data, but then I found out that sending, for example, the LED ON command also triggers the weight updates.

I also found out that the notification callback then receives the information regard button presses, led on/off (i.e. unit and battery status), tare command responses and possibly also timer responses (however that is not written in the API description)

I played around with that a bit and will prepare a PR when I'm ready, if you like!

**Comment by reox** [comment]
weird enough: now the scale starts to send notification as soon as I enable notifications, without having send any command before...
do you know by chance what the expected behaviour here is?

**Comment by lucapinello** [comment]
Hey thanks for taking a look at my preliminary code.g. Long story short the
problem is the current way I am using the async loop.
 I will push this weekend an update that fixes the glitches you are seeing.

Thanks for the feedback.

**Comment by reox** [comment]
I had never worked with asyncio before, so it is a good training code for me :D
So far, I also noticed that the notification handler would sometimes simply stop getting new notifications.
That sounds like the issue you are describing.
Looking forward for your fixes & happy to test them :)

**Comment by reox** [comment]
I wrote a short script to check the jitter of the notifications. And there I noticed, I have to send led on to make notifications appear. It looks like I only get notifications after the scale shows APP on the display, and I only get this when I send the led command (or another command).
Furthermore, I noticed that there seems to be notification loss - at least here on my Win10 machine - and sometimes there are seconds long no notifications. Do you have the same behavior?

**Comment by lucapinello** [comment]
Yes I noticed the same problem and now added commands in the connect method that are not visible to get the APP. Also for the notification loss I believe is now fixed. Please let me know if this new version works for you.

**Comment by reox** [comment]
Nice! I just pulled your changes, unfortunately, the scale is still a bit fuzzy.
If I run the demo code from the README, I do not see any weight changes incoming.
However, that might just be a Windows thing.

Attached is my crude jittertest script (actually it is not quite jitter but simply the time between notifications). These are my results on a Windows 10 Notebook:

```
received 94 packets
Duration:  10194.23291015625 ms
min, max:  32.526123046875 261.338134765625
mean+-sd 100.28495936239919 54.36369039182432
median,iqr 98.976806640625 98.35595703125
```

And this is the optimal case, when I reran the script, I get this result:
```
received 31 packets
Duration:  13576.017578125 ms
min, max:  16.639892578125 1783.613037109375
mean+-sd 431.23115234375 398.7467937941259
median,iqr 325.084228515625 262.54718017578125
```

I can test next week with a linux machine, maybe this is related to the bluetooth stack of the operating system.

[jittertest.py.txt](https://github.com/lucapinello/pydecentscale/files/6986036/jittertest.py.txt)
(pls note that the scale's mac address is hardcoded in the script)

**Comment by reox** [comment]
I debugged this a bit and it looks like that this loop is the culprit:
```
for i in range(50):
    if ds.weight:
        print('current weight:%.1f' % ds.weight, end='\r')
    asyncio.run( asyncio.sleep(0.1))
```

`ds.weight` is always None for me during the execution, however if I add a print into the notification handler, I see notifications arriving and setting weight. But I do not understand why the value can not be read from the `ds` object?

**Comment by lucapinello** [comment]
Thanks for testing it on windows! I think your hint is right. Probably what is going on here is that the thread running the asyncio loop and the thread where you are defining the class have separate memory on windows so they cannot exchange data. 

You could potentially try to define shared memory variable with multiprocessing, I think they have an object called 'Value' to share simple float/int but I am not sure this is compatible with asyncio.  The other one is to use contextvars but I never tested this before either: https://www.linw1995.com/en/blog/How-To-Write-Asynchronous-Code-With-Contextvars-Properly/

Unfortunately I don't have a Windows machine to test this and thanks for the help improving this library!

**Comment by reox** [comment]
I'm happy to help with testing it on Windows ;)

I think the easiest way would be to implement a producer/consumer queue to exchange values. There is an example in the bleak repo for that. Eventually, you want something to put values into matplotlib and then you want them as list.

**Comment by reox** [comment]
I'm finally had a test on Linux and the jitter is much much better there:
```
received 93 packets
Duration:  10002.7490234375 ms
min, max:  49.900390625 160.0322265625
mean+-sd 100.43436332370923 21.386606314208038
median,iqr 100.1578369140625 39.9815673828125
```

Not sure what the Windows bleak backend does, but for sure nothing good :/
The only thing I noticed on Linux is, that sometimes my BT keyboard and mouse get disconnected when the scale is connected oO
