### ISSUE TITLE
pydecentscale package version compatibilities

### ISSUE THREAD

**Issue by rcfberg** [lucapinello/pydecentscale#5]
Hi,

Great project! Attempting to run the code, which are the supported versions of Python and various other dependencies?

Thanks !

/Robin

**Comment by lucapinello** [comment]
Thanks Robin!

Python3, the deps are listed are in the setup.py file.

**Comment by lucapinello** [comment]
Thanks Robin.

Python3, the deps are listed are in the setup.py file.
